# linear control, for ik drive


CHANNEL_CONFIGS:

    pump:
        input_channel: None
        output_channel: 9
        direction: 1
        #center: 1500        # pump does not use this
        pulse_min: 1000     # Full range for ESC
        pulse_max: 1700     # limit the max speed alot
        idle: 0.40          # Gives nice idle speed for pump
        multiplier: 0.4    # Pump speed increase factor

    lift_boom:
        input_channel: 1
        output_channel: 3
        affects_pump: True
        toggleable: False
        center: 1500
        direction: 1
        gamma_positive: 0.7 # we want to go up a bit more aggressive. Maybe test with different pulse max as well!
        gamma_negative: 0.7
        pulse_min: 1100 # extend
        pulse_max: 1900 # retract
        deadzone: 7


    tilt_boom:
        input_channel: 4
        output_channel: 4
        affects_pump: True
        toggleable: False
        center: 1500
        direction: 1
        gamma_positive: 0.7
        gamma_negative: 0.7
        pulse_min: 1100 # retract
        pulse_max: 1900 # extend
        deadzone: 7


    scoop:
        input_channel: 0
        output_channel: 2
        affects_pump: True # we can leave this true but use toggle_pump_variable(False) in the controller for static speed
        toggleable: False
        center: 1500
        direction: -1
        gamma_positive: 0.7
        gamma_negative: 0.7
        pulse_min: 1100 # direction -1, so extend
        pulse_max: 1900 # retract
        deadzone: 7

    extra_1:
        input_channel: 2
        output_channel: 8
        affects_pump: True
        toggleable: True
        center: 1500
        direction: 1
        gamma_positive: 1.0
        gamma_negative: 1.0
        pulse_min: 1100
        pulse_max: 1900
        deadzone: 0

    extra_2:
        input_channel: 5
        output_channel: 10
        affects_pump: True
        toggleable: True
        center: 1500
        direction: 1
        gamma_positive: 1.0
        gamma_negative: 1.0
        pulse_min: 1100
        pulse_max: 1900
        deadzone: 0

    rotate:
        input_channel: 3
        output_channel: 5
        affects_pump: False
        toggleable: True
        center: 1550
        direction: -1
        gamma_positive: 1.0
        gamma_negative: 1.0
        pulse_min: 1460
        pulse_max: 1620
        deadzone: 0

    trackL:
        input_channel: 7
        output_channel: 0
        affects_pump: False
        toggleable: True
        center: 1500
        direction: -1
        gamma_positive: 1.0
        gamma_negative: 1.0
        pulse_min: 1000
        pulse_max: 1700
        deadzone: 10

    trackR:
        input_channel: 6
        output_channel: 1
        affects_pump: False
        toggleable: True
        center: 1500        # set to None for automatic centering ((min+max)/2)
        direction: 1
        gamma_positive: 1.0
        gamma_negative: 1.0
        pulse_min: 1000     # Conservative range for servos
        pulse_max: 1700
        deadzone: 10         # % from total range
