# Config file for AI-MaSi excavator with updated PCA format
CHANNEL_CONFIGS:

    #pump:
    #    input_channel: None
    #    output_channel: 9


    trackR:
        input_channel: 6
        output_channel: 0
        affects_pump: False
        toggleable: True
        center: 1500        # set to None for automatic centering ((min+max)/2)
        direction: 1
        gamma_positive: 0.2
        gamma_negative: 0.2
        pulse_min: 1100     # Conservative range for servos
        pulse_max: 1900
        deadzone: 0         # % from total range

    trackL:
        input_channel: 7
        output_channel: 1
        affects_pump: False
        toggleable: True
        center: 1500
        direction: 1
        gamma_positive: 0.2
        gamma_negative: 0.2
        pulse_min: 1100
        pulse_max: 1900
        deadzone: 0

    scoop:
        input_channel: 0
        output_channel: 2
        affects_pump: True
        toggleable: False
        center: 1500
        direction: -1
        gamma_positive: 0.2
        gamma_negative: 0.2
        pulse_min: 1100
        pulse_max: 1900
        deadzone: 0

    lift_boom:
        input_channel: 1
        output_channel: 3
        affects_pump: True
        toggleable: False
        center: 1500
        direction: -1
        gamma_positive: 0.2
        gamma_negative: 0.2
        pulse_min: 1100
        pulse_max: 1900
        deadzone: 0

    tilt_boom:
        input_channel: 4
        output_channel: 4
        affects_pump: True
        toggleable: False
        center: 1500
        direction: 1
        gamma_positive: 0.2
        gamma_negative: 0.2
        pulse_min: 1100
        pulse_max: 1900
        deadzone: 0

    rotate:
        input_channel: 3
        output_channel: 5
        affects_pump: False
        toggleable: False
        center: 1500
        direction: -1
        gamma_positive: 1.0
        gamma_negative: 1.0
        pulse_min: 1100
        pulse_max: 1900
        deadzone: 0

    tool1:
        input_channel: 5
        output_channel: 6
        affects_pump: False
        toggleable: False
        center: 1500
        direction: 1
        gamma_positive: 1.0
        gamma_negative: 1.0
        pulse_min: 1100
        pulse_max: 1900
        deadzone: 0

    tool2:
        input_channel: 2
        output_channel: 7
        affects_pump: True
        toggleable: False
        center: 1500
        direction: 1
        gamma_positive: 1.0
        gamma_negative: 1.0
        pulse_min: 1100
        pulse_max: 1900
        deadzone: 0