# Config file for student excavator with updated PCA format
# NOT THE AI-MASI EXCAVATOR! Cables are short, thats why the I/O is different.

# TODO: check errors, log all of them before raising. Small QoL.

CHANNEL_CONFIGS:

    pump:
        input_channel: None
        output_channel: 15
        direction: 1
        #center: 1500        # pump does not use this
        pulse_min: 1000     # Full range for ESC
        pulse_max: 1600     # limit the max speed alot
        idle: 0.40          # Gives nice idle speed for pump
        multiplier: 0.50    # Pump speed increase factor

    trackR:
        input_channel: 5
        output_channel: 6
        affects_pump: False
        toggleable: True
        center: 1500        # set to None for automatic centering ((min+max)/2)
        direction: 1
        gamma_positive: 1.0
        gamma_negative: 1.0
        pulse_min: 1000     # Conservative range for servos
        pulse_max: 1700
        deadzone: 10         # % from total range

    trackL:
        input_channel: 4
        output_channel: 7
        affects_pump: False
        toggleable: True
        center: 1500
        direction: 1
        gamma_positive: 1.0
        gamma_negative: 1.0
        pulse_min: 1000
        pulse_max: 1700
        deadzone: 10

    scoop:
        input_channel: 0
        output_channel: 2
        affects_pump: True
        toggleable: False
        center: 1500
        direction: -1
        gamma_positive: 0.2
        gamma_negative: 0.2
        pulse_min: 1100
        pulse_max: 1900
        deadzone: 10

    lift_boom:
        input_channel: 3
        output_channel: 3
        affects_pump: True
        toggleable: False
        center: 1400
        direction: -1
        gamma_positive: 1.0
        gamma_negative: 1.0
        pulse_min: 1100
        pulse_max: 2000
        deadzone: 5

    tilt_boom:
        input_channel: 1
        output_channel: 4
        affects_pump: True
        toggleable: False
        center: 1500
        direction: 1
        gamma_positive: 0.2
        gamma_negative: 0.2
        pulse_min: 1100
        pulse_max: 1900
        deadzone: 10

    rotate:
        input_channel: 2
        output_channel: 5
        affects_pump: False
        toggleable: False
        center: 1500
        direction: 1
        gamma_positive: 1.0
        gamma_negative: 1.0
        pulse_min: 1460
        pulse_max: 1620
        deadzone: 10

    tool1:
        input_channel: 6
        output_channel: 0 # short cables
        affects_pump: True
        toggleable: False
        center: 1500
        direction: 1
        gamma_positive: 1.0
        gamma_negative: 1.0
        pulse_min: 1100
        pulse_max: 1900
        deadzone: 20

    tool2:
        input_channel: 7
        output_channel: 1   # short cables
        affects_pump: True
        toggleable: False
        center: 1500
        direction: 1
        gamma_positive: 1.0
        gamma_negative: 1.0
        pulse_min: 1100
        pulse_max: 1900
        deadzone: 20

    extra0:
        input_channel: 8
        output_channel: 8
        affects_pump: False
        toggleable: False
        center: 1500
        direction: 1
        gamma_positive: 1.0
        gamma_negative: 1.0
        pulse_min: 1100
        pulse_max: 1900
        deadzone: 5

    extra2:
        input_channel: 9
        output_channel: 9
        affects_pump: False
        toggleable: False
        center: 1500
        direction: 1
        gamma_positive: 1.0
        gamma_negative: 1.0
        pulse_min: 1100
        pulse_max: 1900
        deadzone: 5

    extra3:
        input_channel: 10
        output_channel: 10
        affects_pump: False
        toggleable: False
        center: 1500
        direction: 1
        gamma_positive: 1.0
        gamma_negative: 1.0
        pulse_min: 500
        pulse_max: 2500
        deadzone: 5

    extra4:
        input_channel: 11
        output_channel: 11
        affects_pump: False
        toggleable: False
        center: None
        direction: 1
        gamma_positive: 1.0
        gamma_negative: 1.0
        pulse_min: 500
        pulse_max: 2500
        deadzone: 5

    extra5:
        input_channel: 12
        output_channel: 12
        affects_pump: False
        toggleable: False
        center: None
        direction: 1
        gamma_positive: 1.0
        gamma_negative: 1.0
        pulse_min: 500
        pulse_max: 2500
        deadzone: 5

    extra6:
        input_channel: 13
        output_channel: 13
        affects_pump: False
        toggleable: False
        center: None
        direction: 1
        gamma_positive: 1.0
        gamma_negative: 1.0
        pulse_min: 500
        pulse_max: 2500
        deadzone: 5
