# Config file for AI-MaSi excavator with updated PCA format
# linear control, for ik drive

# TODO: should we take out the deadzone with gamma, or to code it in the PD controller?


CHANNEL_CONFIGS:

    #pump:
    #    input_channel: None
    #    output_channel: 15
    #    direction: 1
        #center: 1500        # pump does not use this
    #    pulse_min: 1000     # Full range for ESC
    #    pulse_max: 1600     # limit the max speed alot
    #    idle: 0.40          # Gives nice idle speed for pump
    #    multiplier: 0.50    # Pump speed increase factor

    scoop:
        input_channel: 0
        output_channel: 2
        affects_pump: True # we can leave this true but use toggle_pump_variable(False) in the controller for static speed
        toggleable: False
        center: 1500
        direction: -1
        gamma_positive: 1.0
        gamma_negative: 1.0
        pulse_min: 1100
        pulse_max: 1900
        deadzone: 0

    lift_boom:
        input_channel: 1
        output_channel: 3
        affects_pump: True
        toggleable: False
        center: 1400
        direction: -1
        gamma_positive: 1.0
        gamma_negative: 1.0
        pulse_min: 1100
        pulse_max: 2000
        deadzone: 0

    tilt_boom:
        input_channel: 2
        output_channel: 4
        affects_pump: True
        toggleable: False
        center: 1500
        direction: 1
        gamma_positive: 0.2
        gamma_negative: 0.2
        pulse_min: 1100
        pulse_max: 1900
        deadzone: 0


    #rotate:
    #    input_channel: 3
    #    output_channel: 5
    #    affects_pump: False
    #    toggleable: False
    #    center: 1500
    #    direction: 1
    #    gamma_positive: 1.0
    #    gamma_negative: 1.0
    #    pulse_min: 1460
    #    pulse_max: 1620
    #    deadzone: 0